basePath: /v1
definitions:
  domain.FeiraLivre:
    properties:
      areap:
        type: integer
      bairro:
        type: string
      codDist:
        type: integer
      codSubPref:
        type: integer
      distrito:
        type: string
      id:
        type: integer
      lat:
        type: integer
      logradouro:
        type: string
      long:
        type: integer
      nomeFeira:
        type: string
      numero:
        type: string
      referencia:
        type: string
      regiao5:
        type: string
      regiao8:
        type: string
      registro:
        type: string
      setCens:
        type: integer
      subPref:
        type: string
    type: object
  domain.FeiraLivrePersist:
    properties:
      areap:
        type: integer
      bairro:
        type: string
      codDist:
        type: integer
      codSubPref:
        type: integer
      distrito:
        type: string
      lat:
        type: integer
      logradouro:
        type: string
      long:
        type: integer
      nomeFeira:
        type: string
      numero:
        type: string
      referencia:
        type: string
      regiao5:
        type: string
      regiao8:
        type: string
      registro:
        type: string
      setCens:
        type: integer
      subPref:
        type: string
    type: object
  domain.FeiraLivreUpdate:
    properties:
      areap:
        type: integer
      bairro:
        type: string
      codDist:
        type: integer
      codSubPref:
        type: integer
      distrito:
        type: string
      lat:
        type: integer
      logradouro:
        type: string
      long:
        type: integer
      nomeFeira:
        type: string
      numero:
        type: string
      referencia:
        type: string
      regiao5:
        type: string
      regiao8:
        type: string
      setCens:
        type: integer
      subPref:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
paths:
  /feiras:
    get:
      consumes:
      - application/json
      description: Displays all feiras registered on the API.
      parameters:
      - description: Name of the distrito
        in: query
        name: distrito
        type: string
      - description: Name of regiao5
        in: query
        name: regiao5
        type: string
      - description: Name of feira
        in: query
        name: nomefeira
        type: string
      - description: Name of bairro
        in: query
        name: bairro
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.FeiraLivre'
            type: array
        "204":
          description: Feiras not found
      summary: List feiras
      tags:
      - Feiras
    post:
      consumes:
      - application/json
      description: Creates a new feira
      parameters:
      - description: Object for persisting the feira
        in: body
        name: content
        required: true
        schema:
          $ref: '#/definitions/domain.FeiraLivrePersist'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.FeiraLivre'
        "400":
          description: Bad request
      summary: Create a feira
      tags:
      - Feiras
  /feiras/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a feira by id
      parameters:
      - description: The identifier for the feira
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: Deleted
        "204":
          description: Feira not found
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: Delete a feira
      tags:
      - Feiras
    get:
      consumes:
      - application/json
      description: Get a feira
      parameters:
      - description: The identifier for the feira
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.FeiraLivre'
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: Get a feira
      tags:
      - Feiras
    put:
      consumes:
      - application/json
      description: Updates a feira
      parameters:
      - description: The identifier for the feira
        in: path
        name: id
        required: true
        type: string
      - description: Object for updating a feira
        in: body
        name: content
        required: true
        schema:
          $ref: '#/definitions/domain.FeiraLivreUpdate'
      responses:
        "200":
          description: Ok
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: Update a feira
      tags:
      - Feiras
  /feiras/registro/{registro}:
    delete:
      consumes:
      - application/json
      description: Delete a feira by id
      parameters:
      - description: The identifier for the feira
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: Deleted
        "204":
          description: Feira not found
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: Delete a feira
      tags:
      - Feiras
securityDefinitions:
  carrierIdAuthentication:
    in: header
    name: carrierId
    type: apiKey
swagger: "2.0"
